# Generated by Django 3.1.4 on 2021-02-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_auto_20210219_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='email',
            field=models.EmailField(default=2, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
